""" Training Random Forest Classifier Algorithm on PPI feature space with Foldseek-integrated features.
    Andrew Chung, hc893; Optimized on 8/7/2025, Updated 8/8/2025
"""

import warnings
warnings.filterwarnings("ignore")

import os
import sys
import json
import argparse
import logging
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from cycler import cycler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    roc_auc_score, roc_curve, precision_recall_curve, average_precision_score
)
from xgboost import XGBClassifier

sys.path.append(os.path.abspath(os.path.join(
    os.path.dirname(__file__), '..'))
)

# modify directories for G2
DEFAULT_USER_BASE_DIR = "/home/hc893"
DEFAULT_DATA_PATH = os.path.join(DEFAULT_USER_BASE_DIR, "data/features.csv")
DEFAULT_TEMPLATES_PATH = os.path.join(DEFAULT_USER_BASE_DIR, "data/template-data")
DEFAULT_OUTPUT_PATH = os.path.join(DEFAULT_USER_BASE_DIR, "projects/ppi-classifiers/figures/")
RANDOM_STATE = 893

# Configure logging
logging.basicConfig(
    level = logging.INFO,
    format = '%(asctime)s - %(levelname)s - %(message)s',
    handlers = [logging.StreamHandler()]
)

# refine figure aesthetics
extended_colors = [
    "#CEDC9A",  # light green
    "#80C9C0",  # teal
    "#5A9ED9",  # sky blue
    "#B8B4E8",  # lavender
    "#505A9C",  # navy
    "#F4A582",  # warm peach
    "#D96F9C",  # soft magenta
    "#F7E1A1",  # soft yellow
    "#E8A978",  # apricot
    "#C37B89",  # dusty rose
    "#9CBFA7",  # sage green
    "#4E8E89",  # darker teal
    "#82628C",  # muted plum
    "#A9907E",  # taupe
    "#8D99AE"   # slate grey
]
plt.style.use('bmh')
plt.rcParams.update({
    # figure
    'figure.facecolor': 'white',
    'figure.dpi': 150,

    # axes
    'axes.facecolor': 'white',
    'axes.edgecolor': '0.2',         # dark grey axis lines
    'axes.grid': True,
    'grid.color': '0.8',             # light grey grid
    'grid.linestyle': '--',
    'grid.linewidth': 1,
    'axes.axisbelow': True,          # grid below the plot
    'axes.prop_cycle': cycler(
        'color', extended_colors
    ),

    # lines
    'lines.linewidth': 2,
    'lines.markersize': 6,

    # fonts
    # 'font.family': 'serif',
    # 'font.serif': ['Palatino Linotype'],
    # 'font.size': 12,

    # ticks
    'xtick.color': '0.2',
    'ytick.color': '0.2',
    'xtick.direction': 'out',
    'ytick.direction': 'out',

    # legend
    'legend.frameon': True,
    'legend.framealpha': 1.0,
    'legend.edgecolor': '0.2',
    'legend.fontsize': 10,
})

def extract_templates(data: pd.DataFrame, template_path: str = DEFAULT_TEMPLATES_PATH):
    """ This function extracts the template data from the .json files generated by
        generate_top_templates.py. The template data is then mereged and used to train the classifiers.
    """
    if not os.path.exists(template_path):
        logging.error(f"Error: Path {template_path} cannot be resolved.")
        return data
    if not 'ppi' in data.columns or not 'label' in data.columns:
        logging.error(f"Error: Data file is missing either column 'label' or 'ppi'.")
        return data
    dcopy = data.copy().assign(has_templates = 0, fident = 0, pident = 0, evalue = 0, SIZE = 0, COV = 0)

    erroneous_pairs = []
    for index, row in dcopy.iterrows():
        p1, p2 = row['ppi'].split(':')
        try:
            with open(os.path.join(template_path, f"{p1}_{p2}.json"), 'r') as infile:
                template = json.load(infile)
        except Exception as e:
            # since template-dependent features are defaulted at 0, the row will simply be skipped
            erroneous_pairs.append(f'{p1}_{p2}')
            logging.warning(f"Error: unable to import {p1}_{p2}.json from specified directory.")
            continue

        # No templates detected for given query pair
        if template.get('pdb_id') is None or template.get('chain_ids') is None:
            continue
        # Transcribe .json values into Data Frame
        dcopy.loc[index, 'has_templates'] = 1
        dcopy.loc[index, 'fident'] = template.get('fident', 0)
        dcopy.loc[index, 'pident'] = template.get('pident', 0)
        dcopy.loc[index, 'evalue'] = template.get('e_value', 0)
        dcopy.loc[index, 'SIZE'] = template.get('SIZE', 0)
        dcopy.loc[index, 'COV'] = template.get('COV', 0)
    
    if not erroneous_pairs: # template data for all queries successfully transcribed
        logging.info(f"Template data for all {len(dcopy)} query pairs were successfully transcribed.")
    else:
        logging.warning(f"Warning: template data was not successfully transcribed for {len(erroneous_pairs)}/{len(dcopy)} query pairs.")
        print(erroneous_pairs)
    
    return dcopy

def compute_metrics(y_test, y_prob) -> dict:
    """ Given either y_test and y_prob from a trained RFC or pre-computed 
        PrePPI probabilistic scores, compute the following metrics:
        --- fpr: False Positive Rate (FPR)
        --- tpr: True Positive Rate (TPR)
        --- precision: Precision
        --- recall: Recall
        --- roc_auc: ROC curve AUC
        --- pr_auc: PR curve AUC
        --- ap_score: Average Precision
    """
    if len(y_test) == 0:
        logging.warning("Warning: y_test is empty, cannot compute metrics.")
        return {
            'fpr': np.array([0,1]), 'tpr': np.array([0,1]), 
            'precision': np.array([0,1]), 'recall': np.array([1,0]),
            'roc_auc': 0.0, 'pr_auc': 0.0, 'ap_score': 0.0
        }
    if len(np.unique(y_test)) < 2:
        logging.warning(f"Warning: y_test has only one class ({np.unique(y_test)[0]})")
        num_actual_positives = np.sum(y_test == 1)
        baseline_pr = num_actual_positives / len(y_test) if len(y_test) > 0 else 0.0
        return {
            'fpr': np.array([0,1]), 'tpr': np.array([0,1]), 
            'precision': np.array([baseline_pr, baseline_pr]), 'recall': np.array([1,0]),
            'roc_auc': 0.5, 'pr_auc': baseline_pr, 'ap_score': baseline_pr
        }
    
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    precision, recall, _ = precision_recall_curve(y_test, y_prob)
    roc_auc = roc_auc_score(y_test, y_prob)
    ap_score = average_precision_score(y_test, y_prob)
    return {
        'fpr': fpr, 'tpr': tpr,
        'precision': precision, 'recall': recall,
        'roc_auc': roc_auc, 'pr_auc': ap_score, 'ap_score': ap_score
    }

def train_rfc(X_train, y_train, X_test, y_test, n_estimators: int = 500, random_state = RANDOM_STATE):
    """ Train a Random Forest Classifier on the train data and return 
        a structured output of classification metrics (see above) as a dict object.
        A helper function, compute_metrics(), is defined above to calculate aforementioned metrics.
    """

    rfc = RandomForestClassifier(
        n_estimators = n_estimators, 
        oob_score = True,
        random_state = random_state
    )
    rfc.fit(X_train, y_train)
    y_prob = rfc.predict_proba(X_test)[:, 1]
    return compute_metrics(y_test, y_prob), y_prob

def train_xgb(X_train, y_train, X_test, y_test, n_estimators: int = 500, scale_pos_weight: float = 1.0, random_state = RANDOM_STATE):
    """ Train an XGBoost Classifier on the train data and return 
        a structured output of classification metrics (see above) as a dict object.
        A helper function, compute_metrics(), is defined above to calculate aforementioned metrics.
    """

    xgb = XGBClassifier(
        n_estimators = n_estimators, learning_rate = 0.1, random_state = random_state,
        max_depth = 5, subsample = 0.8, colsample_bytree = 0.8, scale_pos_weight = scale_pos_weight,
        objective = 'binary:logistic', eval_metric = 'logloss'
    )
    xgb.fit(X_train, y_train)
    y_prob = xgb.predict_proba(X_test)[:, 1]
    return compute_metrics(y_test, y_prob), y_prob

def plot_roc_pr(
        results: dict, 
        axes, 
        classifier_name: str
    ):
    """ Plot ROC/PR curves for the given classifier results.
        NOTE: this function does not handle class ratios. see plot_roc_pr_with_ratios() for that.
    --- 'axes' must conform to a 1x2 grid, respectively for ROC and PR curves.
    """

    # plot ROC curve
    sns.lineplot(
        x = results['fpr'], y = results['tpr'], ax = axes[0],
        label = f"{classifier_name} (AUROC = {results['roc_auc']:.3f})", linewidth = 1.5, ci = None
    )
    axes[0].set_title('Receiver Operating Characteristic (ROC)', fontsize = 12)
    axes[0].set_xlabel('False Positive Rate', fontsize = 12)
    axes[0].set_ylabel('True Positive Rate', fontsize = 12)
    axes[0].legend(loc = 'lower right', facecolor = 'white', fontsize = 8)
    axes[0].plot([0, 1], [0, 1], linestyle = '--', color = 'gray', alpha = 0.5) # diagonal line

    # plot PR curve
    sns.lineplot(
        x = results['recall'], y = results['precision'], ax = axes[1],
        label = f"{classifier_name} (AUPR = {results['pr_auc']:.3f})", linewidth = 1.5, ci = None
    )
    axes[1].set_title('Precision Recall (PR)', fontsize = 12)
    axes[1].set_xlabel('Recall', fontsize = 12)
    axes[1].set_ylabel('Precision', fontsize = 12)
    axes[1].legend(loc = 'best', facecolor = 'white', fontsize = 8)
    axes[1].set_ylim([0.0, 1.05])

    # figure aesthetics
    for ax in axes:
        ax.tick_params(axis = 'both', which = 'major', labelsize = 12)

def plot_roc_pr_with_ratios(results: dict, axes, cind, plot_title_detail, clf_type = None) -> None:
    """ Plot ROC/PR curves and refines figure aesthetics. 
    --- results should be a dict object with the key:value pairs prescribed in compute_metrics above.
    --- axes: the axes on which your plots are superimposed.
    --- cind: (for grid-arranged axes) column index
    --- plot_title_detail: customizable
    --- clf_type: nature of the data set (e.g. features used, data source)
    """
    # plot ROC curve
    sns.lineplot(
        x = results['fpr'], y = results['tpr'], ax = axes[0, cind], 
        label = f"{clf_type} ({results['roc_auc']:.3f})",
        linewidth = 1.5, ci = None
    )
    axes[0, cind].set_title(f"Test set: {plot_title_detail}", fontsize = 12)
    axes[0, cind].set_xlabel("False Positive Rate", fontsize = 10)
    axes[0, cind].set_ylabel("True Positive Rate", fontsize = 10)
    axes[0, cind].legend(loc = 'lower right', facecolor = 'white', fontsize = 6)
    axes[0, cind].plot([0, 1], [0, 1], linestyle = '--', color = 'gray', alpha = 0.5)

    # plot PR curve
    sns.lineplot(
        x = results['recall'], y = results['precision'], ax = axes[1, cind],
        label = f"{clf_type} ({results['pr_auc']:.3f})",
        linewidth = 1.5, ci = None
    )
    axes[1, cind].set_xlabel('Recall', fontsize = 10)
    axes[1, cind].set_ylabel('Precision', fontsize = 10)
    axes[1, cind].legend(loc = 'best', facecolor = 'white', fontsize = 6)
    axes[1, cind].set_ylim([0.0, 1.05])

    # refine figure aesthetics
    for row in range(2):
        axes[row, cind].tick_params(axis = 'both', which = 'major', labelsize = 8)

def analyze_predictions(
        y_test: pd.Series, 
        y_prob: pd.Series, 
        model_name, 
        test_set_desc
    ):
    y_test, y_prob = np.asarray(y_test), np.asarray(y_prob)
    n_pos_test, n_neg_test = sum(y_test == 1), sum(y_test == 0)

    if len(y_test) == 0:
        print("Test set is empty for analysis.")
        return
    
    baseline_precision = n_pos_test / len(y_test) if len(y_test) > 0 else 0.0
    pos_scores = y_prob[y_test == 1] if n_pos_test > 0 else np.array([])
    neg_scores = y_prob[y_test == 0] if n_neg_test > 0 else np.array([])

    print(f"\n=== {model_name} - Test Set Details: {test_set_desc} ===")
    print(f"Actual Test Composition: {n_pos_test} P, {n_neg_test} N (Baseline Precision: {baseline_precision:.4f})")
    
    print("Positive scores - {}".format(
        f"Mean: {pos_scores.mean():.4f}, Med: {np.median(pos_scores):.4f}, SD: {pos_scores.std():.4f}" if len(pos_scores) > 0 else "No positive samples in this test set."
    ))
    print("Negative scores - {}".format(
        f"Mean: {neg_scores.mean():.4f}, Med: {np.median(neg_scores):.4f}, SD: {neg_scores.std():.4f}" if len(neg_scores) > 0 else "No negative samples in this test set."
    ))
    if len(pos_scores) > 0 and len(neg_scores) > 0:
        print(f"Score separation (mean(P) - mean(N)) = {pos_scores.mean() - neg_scores.mean():.4f}")

    for threshold in np.array([0.1, 0.5, 0.9]):
        n_pred_over_thr = np.sum(y_prob >= threshold)
        if n_pred_over_thr > 0:
            tp_at_thr = np.sum((y_prob >= threshold) & (y_test == 1))
            precision_at_thr = tp_at_thr / n_pred_over_thr
            recall_at_thr = tp_at_thr / n_pos_test if n_pos_test > 0 else 0.0
            print(f"Thr {threshold:.1f}: {n_pred_over_thr} preds, Prec = {precision_at_thr:.4f}, Rec = {recall_at_thr:.4f}")
        else: 
            print(f"Thr {threshold:.1f}: 0 preds")

def manual_resample_training_data(
        X_train: pd.DataFrame, 
        y_train: pd.Series, 
        n_pos_target: int, 
        n_neg_target: int, 
        random_state: int = 893
    ):
    # manual re-sampling of X and y training data to target positive/negative counts.
    rng = np.random.RandomState(random_state)
    X_data_df, y_data_series = X_train.reset_index(drop = True), y_train.reset_index(drop = True)

    pos_df, neg_df = X_data_df[y_data_series == 1], X_data_df[y_data_series == 0]
    n_pos_current, n_neg_current = len(pos_df), len(neg_df)
    
    selected_dfs = []

    # positive samples
    if n_pos_target > 0:
        if n_pos_current == 0:
            print(f"Warning: No positive samples in input data to manual_resample_training_data for target {n_pos_target}.")
        else:
            selected_pos_df = pos_df.sample(
                n = n_pos_target,
                random_state = rng,
                replace = n_pos_target > n_pos_current # oversample only if n_pos_target > n_pos_current
            )
            selected_dfs.append(selected_pos_df)
    
    # negative samples
    if n_neg_target > 0:
        if n_neg_current == 0:
            print(f"Warning: No negative samples in input data to manual_resample_training_data for target {n_neg_target}.")
        else:
            selected_neg_df = neg_df.sample(
                n = n_neg_target,
                random_state = rng,
                replace = n_neg_target > n_neg_current # oversample only if n_neg_target > n_neg_current
            )
            selected_dfs.append(selected_neg_df)

    if not selected_dfs: # no samples available, or both n_pos_target and n_neg_target are 0
        return pd.DataFrame(columns = X_data_df.columns), pd.Series(dtype = int)
    
    X_resampled = pd.concat(selected_dfs)
    y_resampled = y_data_series[X_resampled.index]

    # shuffle combined data
    shuffled_indices = rng.permutation(len(X_resampled))
    X_resampled = X_resampled.iloc[shuffled_indices].reset_index(drop = True)
    y_resampled = y_resampled.iloc[shuffled_indices].reset_index(drop = True)
    return X_resampled, y_resampled

def create_ratioed_test_set_oversample_neg(X_orig_test, y_orig_test, target_neg_multiplier, random_state = 893):
    """
    Creates test sets by keeping all positive samples from X_orig_test and 
    oversampling negative samples (with replacement) from X_orig_test 
    to achieve the target_neg_multiplier (negatives = positives * multiplier).
    """
    rng = np.random.RandomState(random_state)
    
    X_orig_test_df = X_orig_test.reset_index(drop = True)
    y_orig_test_series = y_orig_test.reset_index(drop = True)

    X_pos_all_from_orig_test = X_orig_test_df[y_orig_test_series == 1]
    y_pos_all_from_orig_test = y_orig_test_series[y_orig_test_series == 1]
    
    X_neg_unique_from_orig_test = X_orig_test_df[y_orig_test_series == 0]
    # y_neg_unique_from_orig_test = y_orig_test_series[y_orig_test_series == 0] # Not directly used for sampling y

    n_pos_final = len(X_pos_all_from_orig_test) # Keep all original test positives
    
    if n_pos_final == 0:
        print(f"  Warning: No positive samples in original test data. Cannot create targeted ratio 1:{target_neg_multiplier}.")
        # Return empty or just a few negatives if that's meaningful.
        if len(X_neg_unique_from_orig_test) > 0:
            n_neg_sample = min(10, len(X_neg_unique_from_orig_test)) # Sample a few negatives for consistency
            X_neg_final_df = X_neg_unique_from_orig_test.sample(n = n_neg_sample, random_state = rng, replace = False)
            y_neg_final_series = y_orig_test_series.loc[X_neg_final_df.index] # Get original labels for these negatives
            print(f"  Returning {n_neg_sample} unique negative samples as positives are zero.")
            return X_neg_final_df, y_neg_final_series
        return pd.DataFrame(columns = X_orig_test_df.columns), pd.Series(dtype=int)

    n_neg_target = int(round(n_pos_final * target_neg_multiplier)) # Calculate target number of negatives

    # Final positive samples are all original test positives
    X_pos_final_df = X_pos_all_from_orig_test
    y_pos_final_series = y_pos_all_from_orig_test

    # Handle negative samples
    X_neg_final_df = pd.DataFrame(columns = X_orig_test_df.columns) # Initialize empty
    y_neg_final_series = pd.Series(dtype = int)

    if n_neg_target > 0:
        if len(X_neg_unique_from_orig_test) == 0: # No unique negatives to sample from
            print(f"  Warning: No negative samples in original test data to oversample for target ratio 1:{target_neg_multiplier}.")
            # X_neg_final_df remains empty
        else:
            # Oversample from unique negatives with replacement
            # We need to sample indices to correctly get X and y
            sampled_neg_indices = rng.choice(X_neg_unique_from_orig_test.index, size = n_neg_target, replace = True)
            X_neg_final_df = X_neg_unique_from_orig_test.loc[sampled_neg_indices]
            y_neg_final_series = y_orig_test_series.loc[sampled_neg_indices] # Get original labels for these negatives

    # Combine positives and (potentially oversampled) negatives
    X_test_ratioed = pd.concat([X_pos_final_df, X_neg_final_df])
    y_test_ratioed = pd.concat([y_pos_final_series, y_neg_final_series])
    
    # Shuffle the combined test set
    if not X_test_ratioed.empty:
        shuffled_indices = rng.permutation(len(X_test_ratioed))
        X_test_ratioed = X_test_ratioed.iloc[shuffled_indices].reset_index(drop = True)
        y_test_ratioed = y_test_ratioed.iloc[shuffled_indices].reset_index(drop = True)
    
    actual_n_p, actual_n_n = sum(y_test_ratioed == 1), sum(y_test_ratioed == 0)
    actual_final_ratio_str = f"1:{actual_n_n/actual_n_p:.1f}" if actual_n_p > 0 else ("0P" if actual_n_n == 0 else "0P, ManyN")
    print(f"  Target Pos:Neg Ratio 1:{target_neg_multiplier} -> Actual Test Set: "
          f"{actual_n_p}P, {actual_n_n}N (Ratio: {actual_final_ratio_str}). "
          f"Negatives created from {len(X_neg_unique_from_orig_test)} unique negatives (oversampled if needed).")
          
    return X_test_ratioed, y_test_ratioed

def main():

    parser = argparse.ArgumentParser(description = "Foldseek Classifier Training")
    parser.add_argument('--data_path', type = str, default = DEFAULT_DATA_PATH, help = "Training data path.")
    parser.add_argument('--template_data_path', type = str, default = DEFAULT_TEMPLATES_PATH, help = "Path containing template .json files.")
    parser.add_argument('--output_path', type = str, default = DEFAULT_OUTPUT_PATH, help = "Output directory for result figures.")
    args = parser.parse_args()

    logging.info("=== PPI Classifier Training Script ===")
    logging.info("Loading and processing data...")

    # Load comprehensive PPI data set, retain only genomic features, PrePPI criteria, and lable
    try:
        data = pd.read_csv(args.data_path)
        required_cols = np.array(['ppi', 'Total', 'co-expression', 'BP', 'CC', 'MF', 'label'])
        for col in required_cols:
            if col not in data.columns:
                logging.error(f"Data file missing required column: {col}")
                return
        data = data[required_cols]
    except FileNotFoundError:
        logging.error(f"Data file(s) not found.")
        return
    assert 'label' in data.columns and 'ppi' in data.columns, \
        logging.error("Error: either 'label' or 'ppi' column is missing somehow.")

    # import homologous template-based features
    data = extract_templates(data, template_path = args.template_data_path)
    
    # Provide comprehensive overview of training and test data sets
    print(f"{'='*60}\n=== DATASETS OVERVIEW ===")
    print(f"Selected features: {', '.join(data.columns.drop('label'))}")
    print("Head of PPI Data File:")
    print(data.head())

    logging.info(f"{len(data)} PPI pairs found.")
    value_counts = data['label'].value_counts()
    total_pos, total_neg = value_counts.get(1, 0), value_counts.get(0, 0)
    if total_pos == 0 or len(data) < 2:
        logging.error("ERROR: No positive samples or insufficient data. Exiting.")
        return
    
    print(f"Total samples for splitting: {len(data)} ({total_pos} P, {total_neg} N)")
    print(f"Overall P:N ratio: 1:{total_neg/total_pos:.1f}" if total_pos > 0 else "N/A (0 positives)")
    print(f"Overall Baseline precision: {total_pos/(total_pos + total_neg):.4f}" if (total_pos + total_neg) > 0 else "N/A")
    # input("Press Enter to continue...")

    """ Define feature space of all classifiers. 
    --- Classifier 0: PrePPI (Total score)
    --- Classifier 1: Genomic (coexp, BP, CC, MF)
    --- Classifier 2: Genomic + HT, fident
    --- Classifier 3: Genomic + HT, pident
    *** Classifier 4: Genomic + HT, fident, pident
    *** Classifier 5: Genomic + HT, fident, pident, e-value
    --- Classifier 6: Genomic + HT, fident, pident, e-value, SIZE/COV
    *** Classifier 7: Genomic + HT, fident, pident, SIZE/COV
    --- Classifier 8: Genomic + HT, fident, SIZE/COV
    --- Classifier 9: Genomic + HT, pident, SIZE/COV
    --- Classifier 10: Genomic + HT, SIZE/COV

    ### PILOT: XGBoost-based classifiers for promising feature sets.
    --- Classifier A: Genomic + HT, fident/pident
    --- Classifier B: Genomic + HT, SIZE/COV
    """
    
    genomic_features = ['co-expression', 'BP', 'CC', 'MF']
    preppi_features = ['SIZE', 'COV']
    feature_sets = {
        'PrePPI -- total': ['Total'],
        'RF: Genomic': genomic_features,
        'RF: Genomic + HT/fident': genomic_features + ['has_templates', 'fident'],
        'RF: Genomic + HT/pident': genomic_features + ['has_templates', 'pident'],
        # 'RF: Genomic + HT/fident/pident': genomic_features + ['has_templates', 'fident', 'pident'],
        # 'RF: Genomic + HT/fident/pident/e-value': genomic_features + ['has_templates', 'fident', 'pident', 'evalue'],
        'RF: Genomic + HT/fident/pident/e-value/SIZE-COV': genomic_features + ['has_templates', 'fident', 'pident', 'evalue'] + preppi_features,
        # 'RF: Genomic + HT/fident/pident/SIZE-COV': genomic_features + ['has_templates', 'fident', 'pident'] + preppi_features,
        'RF: Genomic + HT/fident/SIZE-COV': genomic_features + ['has_templates', 'fident'] + preppi_features,
        'RF: Genomic + HT/pident/SIZE-COV': genomic_features + ['has_templates', 'pident'] + preppi_features,
        'RF: Genomic + HT/SIZE-COV': genomic_features + ['has_templates'] + preppi_features,

        ### New (tentative) XGBoost classifiers (8/9/2025)
        'XGB: Genomic + HT/fident': genomic_features + ['has_templates', 'fident'],
        'XGB: Genomic + HT/SIZE-COV': genomic_features + ['has_templates'] + preppi_features
    }

    """ Part 1: Full Raw Data File (P:N Ratio 1:4.5). Use all existing PPI pairs to train RFC.
        80-20 Train-Test Split, stratified by label proportions.
    """
    print(f"\n{'='*60}\n")
    print("=== Part 1: Training Classifiers on Full Data ===")
    fig, ax = plt.subplots(1, 2, figsize = (13, 6))
    fig.suptitle(
        f"PrePPI vs. RF Classifier with Genomic and Foldseek Features (P:N Ratio = 1:{(total_neg/total_pos):.1f})", 
        fontsize = 16
    )

    X_train, X_test, y_train, y_test = train_test_split(
        data.drop(columns = 'label'), data['label'],
        test_size = 0.2, random_state = RANDOM_STATE, stratify = data['label']
    )
    y_train = np.asarray(y_train)
    y_test = np.asarray(y_test)

    for clf_id, features in feature_sets.items():

        assert all(feature in data.columns for feature in features), \
            logging.error(f"Error: One or more features {features} not found in data columns.")
        print(f"\n=== Evaluating Classifier {clf_id} ===")
        
        if clf_id == 'PrePPI -- total':
            y_prob = X_test[features].squeeze()
            RESULTS = compute_metrics(y_test, y_prob)
        elif clf_id.split(':')[0] == 'XGB':
            spw = np.sum(y_train == 0) / np.sum(y_train == 1)
            RESULTS, y_prob = train_xgb(X_train[features], y_train, X_test[features], y_test, scale_pos_weight = spw)
        else:
            RESULTS, y_prob = train_rfc(X_train[features], y_train, X_test[features], y_test)

        print(f"Model training complete for classifier {clf_id}.")
        analyze_predictions(
            y_test, y_prob, 
            model_name = clf_id, 
            test_set_desc = ','.join(features)
        )
        # print("Plotting ROC/PR curves...")
        plot_roc_pr(
            results = RESULTS, axes = ax, classifier_name = clf_id
        )
        # print("Complete.")
    
    # finalize figures, save to output directory
    print(f"\n{'='*60}")
    logging.info(f"Part 1: All classifiers have been trained/evaluated. Saving figures...")
    try:
        plt.savefig(os.path.join(args.output_path, 'foldseek_classifiers_fulldata_aug9.png'), bbox_inches = 'tight', dpi = 300)
        plt.close()
        logging.info("Plots saved as 'foldseek_classifiers_fulldata_aug9.png'.")
    except Exception as e:
        logging.error(f"Error saving plots: {e}")
        return
    
    # input("Press Enter to continue...")
          
    """ Part 2: Class Ratio-Based Resampling. Systematically oversample negative pairs to 
        simulate real-world protein interactions.
        Ratios (P:N): 1:1, 1:10, 1:100, 1:1000
        In the same fashion as Part 1, 80-20 Train-Test Split, stratified by label proportions.
    """
    print(f"\n{'='*60}\n")
    print("=== Part 2: Training Classifiers with Class Ratios ===")
    fig, ax = plt.subplots(2, 4, figsize = (20, 8))
    fig.suptitle(
        f"PrePPI (Total) vs. Random Forest Classifier with Genomic and Foldseek Features: Class Ratios", 
        fontsize = 16
    )
    # First, train random forest classifiers on a balanced (constant) 1:1 training set
    X_train_bal, y_train_bal = manual_resample_training_data(
        X_train, pd.Series(y_train), 
        n_pos_target = sum(y_train == 1), n_neg_target = sum(y_train == 1)
    )
    print(f"Balanced training set size: P: {sum(y_train_bal == 1)}, N: {sum(y_train_bal == 0)}")
    y_train_bal = np.asarray(y_train_bal)
    
    # train each RFC on the balanced training set
    # need to store trained RFC objects for test set evaluation
    clf_models = {}
    for clf_id, features in feature_sets.items(): # omit PrePPI (not RF)
        
        assert all(feature in X_train_bal.columns for feature in features), \
            logging.error(f"Error: One or more features {features} not found in data columns.")
        if clf_id != 'PrePPI -- total':
            print(f"Training Classifier {clf_id} with balanced 1:1 train set...")
            if clf_id.split(':')[0] == 'RF':
                rfc = RandomForestClassifier(
                    n_estimators = 500, oob_score = True, random_state = RANDOM_STATE
                )
                rfc.fit(X_train_bal[features], y_train_bal)
                clf_models[clf_id] = rfc
            elif clf_id.split(':')[0] == 'XGB':
                xgb = XGBClassifier(
                    n_estimators = 500, learning_rate = 0.1, random_state = RANDOM_STATE,
                    max_depth = 5, subsample = 0.8, colsample_bytree = 0.8, scale_pos_weight = 1,
                    objective = 'binary:logistic', eval_metric = 'logloss'
                )
                xgb.fit(X_train_bal[features], y_train_bal)
                clf_models[clf_id] = xgb
            else:
                logging.error(f"Error: Unknown Classifier ID detected: {clf_id}")
    print("All classifiers trained on balanced 1:1 training set.")

    """ Now, systematically create test sets with varying class ratios.
        For each ratio, oversample the negative class to achieve the desired ratio.
        Then, evaluate each classifier on the test set and plot ROC/PR curves.
    """
    ratios = np.power(10, np.arange(0, 4))  # 1:1, 1:10, 1:100, 1:1000
    for i, ratio in enumerate(ratios):

        print(f"\n{'='*60}\n=== Target Class Ratio 1:{ratio} ===")
        # Test Set Resampling
        X_test_ratio, y_test_ratio = create_ratioed_test_set_oversample_neg(
            X_test, pd.Series(y_test), target_neg_multiplier = ratio, random_state = 893 + i # slight seed variations
        )
        y_test_ratio = np.asarray(y_test_ratio)
        n_p_test_ratio, n_n_test_ratio = sum(y_test_ratio == 1), sum(y_test_ratio == 0)
        print(f"Test set size: P: {n_p_test_ratio}, N: {n_n_test_ratio}")
        print(f"Overall Baseline Precision: {n_p_test_ratio/(n_p_test_ratio + n_n_test_ratio):.4f}")

        for clf_id, features in feature_sets.items():

            print(f"\n=== Training Classifier {clf_id} with features {features} ===")
            if clf_id == 'PrePPI -- total':
                y_prob = X_test_ratio[features].squeeze()
                RESULTS = compute_metrics(y_test_ratio, y_prob)
            else:
                clf = clf_models[clf_id]
                y_prob = clf.predict_proba(X_test_ratio[features])[:, 1]
                RESULTS = compute_metrics(y_test_ratio, y_prob)
            
            print(f"Model training complete for classifier {clf_id}.")
            analyze_predictions(
                y_test_ratio, y_prob, model_name = clf_id, test_set_desc = ','.join(features)
            )
            # print("Plotting ROC/PR curves...")
            plot_roc_pr_with_ratios(
                results = RESULTS, axes = ax, cind = i, 
                plot_title_detail = None,
                clf_type = clf_id
            )
        
        ax[0, i].set_title(f"Test Set: P:N ~ 1:{ratio} ({n_p_test_ratio}P:{n_n_test_ratio}N)", fontsize = 10)

    # finalize figures, save to output directory
    print(f"\n{'='*60}")
    logging.info(f"All classifiers have been trained/evaluated. Saving figures...")
    try:
        plt.savefig(os.path.join(args.output_path, 'foldseek_classifiers_ratio_aug9.png'), bbox_inches = 'tight', dpi = 300)
        plt.close()
        logging.info("Plots saved as 'foldseek_classifiers_ratio_aug9.png'.")
    except Exception as e:
        logging.error(f"Error saving plots: {e}")
        return
    
    logging.info(f"Job Finished.")

if __name__ == "__main__":
    main()
